// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp_Pak1YEC2_clyGSYbZQuUNaGDlK4y9U',
    appId: '1:403581451594:web:f23219587b5c61af1915b3',
    messagingSenderId: '403581451594',
    projectId: 'ucollect-fac39',
    authDomain: 'ucollect-fac39.firebaseapp.com',
    storageBucket: 'ucollect-fac39.firebasestorage.app',
    measurementId: 'G-8X46L6HKTJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBio2j5Dsc9CuVgVMlCcgkEA8cyotdOEvU',
    appId: '1:403581451594:android:bbf55a20139ea7861915b3',
    messagingSenderId: '403581451594',
    projectId: 'ucollect-fac39',
    storageBucket: 'ucollect-fac39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNJX5BCf9_T9tnJU8CwVQBmPfilVrxJC8',
    appId: '1:403581451594:ios:3b55d41058efb9f41915b3',
    messagingSenderId: '403581451594',
    projectId: 'ucollect-fac39',
    storageBucket: 'ucollect-fac39.firebasestorage.app',
    iosBundleId: 'com.example.ucollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNJX5BCf9_T9tnJU8CwVQBmPfilVrxJC8',
    appId: '1:403581451594:ios:3b55d41058efb9f41915b3',
    messagingSenderId: '403581451594',
    projectId: 'ucollect-fac39',
    storageBucket: 'ucollect-fac39.firebasestorage.app',
    iosBundleId: 'com.example.ucollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp_Pak1YEC2_clyGSYbZQuUNaGDlK4y9U',
    appId: '1:403581451594:web:7bec66816ca919f61915b3',
    messagingSenderId: '403581451594',
    projectId: 'ucollect-fac39',
    authDomain: 'ucollect-fac39.firebaseapp.com',
    storageBucket: 'ucollect-fac39.firebasestorage.app',
    measurementId: 'G-Y02YRZ9B7L',
  );
}
